export const team = [
  {
    id: 1,
    name: "TOM",
    photo: "",
    department: "Cosmic Pioneer",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 2,
    name: "OSCAR",
    photo: "",
    department: "Cosmic Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 3,
    name: "TRABS",
    photo: "",
    department: "Cosmic Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 4,
    name: "KROLING",
    photo: "",
    department: "Cosmic Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 5,
    name: "FELIPE",
    photo: "",
    department: "Cosmic Game Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 6,
    name: "B.HOOD",
    photo: "",
    department: "Cosmic Game Dev",
    info: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  /*
  {
    id: 7,
    name: "SÉRGIO",
    photo: "",
    department: "Cosmic Designer",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 8,
    name: "CHICO",
    photo: "",
    department: "Cosmic Designer",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 9,
    name: "DUKKKHART",
    photo: "",
    department: "Cosmic Composer",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 10,
    name: "JOW",
    photo: "",
    department: "Cosmic 3D Artist",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 11,
    name: "KENNEDY",
    photo: "",
    department: "Cosmic 3D Artist",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 12,
    name: "SHAWN",
    photo: "",
    department: "Cosmic 3D Artist",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 13,
    name: "YSAKI",
    photo: "",
    department: "Cosmic Illustrator",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 14,
    name: "ELLIE",
    photo: "",
    department: "Cosmic Illustrator",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 15,
    name: "DEBBYR",
    photo: "",
    department: "Cosmic Support",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 16,
    name: "NEVETS",
    photo: "",
    department: "Cosmic Advisor",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 17,
    name: "JOSH",
    photo: "",
    department: "Cosmic Advisor",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 18,
    name: "JOSÉ",
    photo: "",
    department: "Cosmic Advisor",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 19,
    name: "RENATO",
    photo: "",
    department: "Cosmic Advisor",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },
  {
    id: 20,
    name: "MOOTZ",
    photo: "",
    department: "Cosmic Advisor",
    info:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
    linkedin: "",
    behance: "",
    www: "",
  },*/
];
